version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./public/images:/app/public/images
    environment:
      - NODE_ENV=production
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-Seawrightadmin123}
      - ADMIN_TOKEN=${ADMIN_TOKEN:-Seawrightadmin123}

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
    restart: always
